<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.da</groupId>
  <artifactId>crystal-report-server-java</artifactId>
  <version>2.1.0</version>
  <name>crystal-report-server-java</name>
  <description>An Crystal Report Server for java</description>
  <properties>
    <java.version>21</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <licenses>
    <license>
      <name>MIT</name>
      <url>https://opensource.org/licenses/MIT</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>Robert Huang</name>
      <email>56649783@qq.com</email>
      <organization>Dedienne Aerospace China ZhuHai</organization>
      <organizationUrl/>
    </developer>
  </developers>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-stack-depchain</artifactId>
        <version>5.1.5</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- vertx  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-launcher-application</artifactId>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-config</artifactId>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-web</artifactId>
    </dependency>
    <!-- db pool - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <dependency>
      <groupId>com.zaxxer</groupId>
      <artifactId>HikariCP</artifactId>
      <version>6.2.1</version>
    </dependency>
    <!-- cache - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
      <version>3.2.4</version>
      <scope>compile</scope>
    </dependency>
    <!-- db driver - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>13.4.0.jre11</version>
    </dependency>
    <dependency>
      <groupId>com.mysql</groupId>
      <artifactId>mysql-connector-j</artifactId>
      <version>8.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.7.11</version>
    </dependency>
    <!-- test   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- lombok - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.46</version>
      <scope>provided</scope>
    </dependency>
    <!-- libs for (Crystal Reports) - - - - - - - - - - - - - - - - - - - - -->
    <dependency>
      <groupId>com.ibm.icu</groupId>
      <artifactId>icu4j</artifactId>
      <version>78.3</version>
    </dependency>
    <dependency>
      <groupId>commons-beanutils</groupId>
      <artifactId>commons-beanutils</artifactId>
      <version>1.11.0</version>
    </dependency>
    <dependency>
      <groupId>commons-collections</groupId>
      <artifactId>commons-collections</artifactId>
      <version>3.2.2</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-configuration2</artifactId>
      <version>2.15.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.20.0</version>
    </dependency>
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.4.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-text</artifactId>
      <version>1.15.0</version>
    </dependency>
    <dependency>
      <groupId>com.github.jai-imageio</groupId>
      <artifactId>jai-imageio-core</artifactId>
      <version>1.4.0</version>
    </dependency>
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20260719</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>2.25.4</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.25.4</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j2-impl</artifactId>
      <version>2.25.4</version>
    </dependency>
    <dependency>
      <groupId>org.ogce</groupId>
      <artifactId>xpp3</artifactId>
      <version>1.1.6</version>
    </dependency>
    <!-- core lib of (Crystal Reports) - - - - - - - - - - - - - - - - - - - - -->
    <!-- Install with: .\install-libs.ps1 -->
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>com.azalea.ufl.barcode</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>CrystalCommon2</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>CrystalReportsRuntime</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>cvom</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>DatabaseConnectors</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>JDBInterface</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>keycodeDecoder</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>logging</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>pfjgraphics</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <dependency>
      <groupId>crystal-reports</groupId>
      <artifactId>QueryBuilder</artifactId>
      <version>12.2.233.5802</version>
    </dependency>
    <!-- End of Crystal Reports dependencies -->
  </dependencies>

  <build>
    <resources>
      <!-- add default resources -->
      <resource>
        <directory>src/main/resources/</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/*.*</include>
        </includes>
      </resource>
    </resources>

    <plugins>
      <!-- copy dependencies to target/lib -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>compile</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
              <stripVersion>true</stripVersion>
              <includeScope>compile</includeScope>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
        </configuration>
      </plugin>
      <!-- skip test -->
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.3</version>
        <configuration>
          <skipTests>true</skipTests>
          <forkCount>1</forkCount>
          <reuseForks>true</reuseForks>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.4.1</version>
      </plugin>
      <!-- keep jar with version and no version at same times -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <copy file="${project.build.directory}/${project.artifactId}-${project.version}.jar" tofile="${project.build.directory}/${project.artifactId}.jar"/>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
